### ISSUE TITLE
Backup multiple databases

### ISSUE THREAD

**Issue by ido1990** [ricardolsmendes/docker-samples#2]
Hi!
Thank you for this great project!
I would like to know if it's possible to backup all databases exist on the MariaDB.

Thank you!

**Comment by ricardolsmendes** [comment]
Hi, @ido1990!
Yes, it's possible. Please take a look at https://linuxize.com/post/how-to-back-up-and-restore-mysql-databases-with-mysqldump. Basically, you need to change a little bit the `mysqldump` command, by adding the `--all-databases` flag to it.
